[project]
name = "auto-reservation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "dotenv>=0.9.9",
    "playwright>=1.56.0",
]
